
package com.mycompany.projetopoo;

import com.mycompany.projetopoo.RegistrarTransacao;
import com.mycompany.projetopoo.SistemaDePagamento;
import com.mycompany.projetopoo.TelaCadastroCliente;
import java.awt.event.ActionEvent;
import java.util.List;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author soares
 */

public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        setSize(600, 400); // tamanho da tela
        setLocationRelativeTo(null); // centraliza na tela
        setTitle("Sistema de Pagamento");
        initComponents();
        getContentPane().setLayout(new java.awt.GridLayout(5, 1, 10, 10));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CadastroCliente = new javax.swing.JButton();
        RegistrarTransacao = new javax.swing.JButton();
        HistoricoTransacao = new javax.swing.JButton();
        SaldoAtual = new javax.swing.JButton();
        Sair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema De Pagamento - Cartório");

        CadastroCliente.setText("Cadastrar Cliente");
        CadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroClienteActionPerformed(evt);
            }
        });

        RegistrarTransacao.setText("Registrar Transação");
        RegistrarTransacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarTransacaoActionPerformed(evt);
            }
        });

        HistoricoTransacao.setText("Histórico de Transações");
        HistoricoTransacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistoricoTransacaoActionPerformed(evt);
            }
        });

        SaldoAtual.setText("Saldo Atual");
        SaldoAtual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaldoAtualActionPerformed(evt);
            }
        });

        Sair.setText("Sair");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(RegistrarTransacao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CadastroCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(SaldoAtual))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(296, 296, 296)
                        .addComponent(Sair, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(HistoricoTransacao)))
                .addContainerGap(292, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(CadastroCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RegistrarTransacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HistoricoTransacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SaldoAtual)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Sair)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SairActionPerformed(ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SairActionPerformed

    private void RegistrarTransacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarTransacaoActionPerformed
        RegistrarTransacao tela = new RegistrarTransacao();
        tela.setVisible(true);
        tela.setLocationRelativeTo(null);
    }//GEN-LAST:event_RegistrarTransacaoActionPerformed

    private void CadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroClienteActionPerformed
        TelaCadastroCliente tela = new TelaCadastroCliente();
        tela.setVisible(true);
        tela.setLocationRelativeTo(null);
    }//GEN-LAST:event_CadastroClienteActionPerformed

    private void HistoricoTransacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistoricoTransacaoActionPerformed
        TelaHistoricoTransacao tela = new TelaHistoricoTransacao();
        tela.setVisible(true);
        tela.setLocationRelativeTo(null);
    }//GEN-LAST:event_HistoricoTransacaoActionPerformed

    private void SaldoAtualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaldoAtualActionPerformed
        SistemaDePagamento sistema = SistemaDePagamento.getInstancia();
        double saldo = sistema.calcularSaldoTotal();
        javax.swing.JOptionPane.showMessageDialog(this,
                "Saldo total de transações: R$ " + String.format("%.2f", saldo));
    }//GEN-LAST:event_SaldoAtualActionPerformed

    /**
     * @param args the command line arguments
     */
    // Em SistemaDePagamento.java ou na TelaPrincipal.main
    public static void main(String[] args) {
        // ... (restante do seu código)

        SistemaDePagamento sistema = SistemaDePagamento.getInstancia();
        List<Servico> listaServicos = sistema.getServicos(); // Chama o novo método

        System.out.println("--- TESTE SERVIÇO DAO ---");
        if (listaServicos.isEmpty()) {
            System.out.println("ERRO: Nenhum serviço encontrado. A tabela 'servico' está vazia ou o SELECT falhou.");
        } else {
            System.out.println("Serviços encontrados: " + listaServicos.size());
            for (Servico s : listaServicos) {
                System.out.println("ID: " + s.getId() + " | Descrição: " + s.getDescricao() + " | Valor: R$" + s.getValor());
            }
        }
    

    java.awt.EventQueue.invokeLater ( new Runnable() {
        

    public void run() {
        new TelaPrincipal().setVisible(true);
    }
});
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CadastroCliente;
    private javax.swing.JButton HistoricoTransacao;
    private javax.swing.JButton RegistrarTransacao;
    private javax.swing.JButton Sair;
    private javax.swing.JButton SaldoAtual;
    // End of variables declaration//GEN-END:variables
}
